### ISSUE TITLE
Ladder limit is ignored

### ISSUE THREAD

**Issue by Ma-Ko-dev** [inferno-collection/Ladders-Reborn#15]
After the Update, i am not sure if before too, the limit for ladders gets ignored. I can take out as many ladders as i want from the vehicle. I put "1" in the amount for the vehicle and still had -1 to the total amount of ladders.

**Comment by cm8263** [comment]
> After the Update, i am not sure if before too, the limit for ladders gets ignored. I can take out as many ladders as i want from the vehicle. I put "1" in the amount for the vehicle and still had -1 to the total amount of ladders.

I cannot reproduce this, can you provide a copy of your `config.json` please.

**Comment by Ma-Ko-dev** [comment]
I dont know how to say this, but this one is on me :D

The default value of "EnableLadderVehicleWhitelist" is false and i didnt notice it. So when its false, i can take out as many ladders as i want from any vehicle as long as the global limit is not reached. This makes sense, im sorry for the false report.
