### ISSUE TITLE
Does it works on Linux?

### ISSUE THREAD

**Issue by peppinoita** [inferno-collection/Ladders-Reborn#4]
Most of the c# resources works on linux but in this case nothing happens with /ladder command.

**Comment by cm8263** [comment]
> Most of the c# resources works on linux but in this case nothing happens with /ladder command.

Send a picture of the files please

**Comment by peppinoita** [comment]
I didn't modifyed anything just uploaded on the server
![image](https://user-images.githubusercontent.com/12203647/193005818-7b06aabd-19ec-4996-8042-b23b3116e51f.png)
Probably I didn't understand your request

**Comment by cm8263** [comment]
> I didn't modifyed anything just uploaded on the server ![image](https://user-images.githubusercontent.com/12203647/193005818-7b06aabd-19ec-4996-8042-b23b3116e51f.png) Probably I didn't understand your request

I wanted to check you were not using the uncompiled source code. What happens when you restart the resource on the fly, what shows up in the console?

**Comment by peppinoita** [comment]
I need to be at home to access the server (I'm in my office). By the way no errors, just normal resouce restart, without errors.

I loaded the compiled version of the script, not the sources.

i will update the ticket this evening with the requested screenshots

**Comment by peppinoita** [comment]
Ok so the command is recognized
![image](https://user-images.githubusercontent.com/12203647/193133018-e1e511e6-da9b-41fb-a94e-f99fbae3fa5c.png)
But nothing happens and I have no message at all in both client and server console
![image](https://user-images.githubusercontent.com/12203647/193133340-6aa04e28-45ab-44a6-ac86-8bc1d51f793d.png)
![image](https://user-images.githubusercontent.com/12203647/193133377-700489f4-230d-4a96-b034-345d9c68b002.png)

**Comment by cm8263** [comment]
> What happens when you restart the resource on the fly, what shows up in the console?

Can you send a screenshot of this, both consoles.

**Comment by peppinoita** [comment]
Client
![image](https://user-images.githubusercontent.com/12203647/193309181-1c0dfe88-a76e-4cf6-9f67-df337c207936.png)
Server
![image](https://user-images.githubusercontent.com/12203647/193309231-ea17a3f1-a396-41bc-8934-12ede419f7f0.png)

**Comment by cm8263** [comment]
Fixed in https://github.com/inferno-collection/Ladders-Reborn/issues/6
