### ISSUE TITLE
Server Script will not initialize on Linux servers

### ISSUE THREAD

**Issue by cm8263** [inferno-collection/Ladders-Reborn#6]
Reported here:

- https://github.com/inferno-collection/Ladders-Reborn/issues/4
- https://canary.discord.com/channels/346941064344764416/534030695647936513/1025231948991443035

### Repro Steps:

1. Download fresh files from GitHub releases
2. Install on Linux server
3. Instance of script `InfernoCollection.LaddersReborn.Server.Main` is not initialized

**Comment by cm8263** [comment]
Client files still work nil issues. Server resource technically starts, but `InfernoCollection.LaddersReborn.Server.Main` is not initialized.

- Attempted re-compliying files
- Attempted rewriting in C# 7.3 instead of C# 10

**Comment by peppinoita** [comment]
I have a linux server at your disposal if needed
